name: nextflow-env
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - python=3.10.0
 - nextflow=23.10.1
 - nf-core=2.11.1
 - openjdk=11.0.20
 - pip=23.3.1
 - multiqc=1.19
 - rich=13.7.0
 - typer=0.9.0
 - nf-test
